In [108]:
import numpy as np

data =np. array ([[1, 5, 6, 7, 4 , 3],
                  [5, 7, 8, 1, 6]])
datalain = np.array([
    [2, 6, 8, 4, 7, 3, 6 ,12, 67, 30],
    [1, 5, 7, 8, 3, 9, 14],
    [5, 7, 9]
])


a =np.sort(data[0])
b = np.sort(data[1])
c = np.sort(datalain[0])
d = np.sort(datalain[1])
e = np.sort(datalain[2])

print(e)
print(b)
print(a)
print(d)
print(c)



[5 7 9]
[1 5 6 7 8]
[1 3 4 5 6 7]
[ 1  3  5  7  8  9 14]
[ 2  3  4  6  6  7  8 12 30 67]
